package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "mercury_common",
    includes = ["*.h"],
    srcs = glob([
        "*.h",
    ]),
    hdrs = glob([
        "*.h",
    ]),
)
