
option(ENABLE_OPENMP "Enable OpenMP support" OFF)
option(ENABLE_SSE "Enable Intel SSE instructions" OFF)
option(ENABLE_SSE2 "Enable Intel SSE2 instructions" OFF)
option(ENABLE_SSE3 "Enable Intel SSE3 instructions" OFF)
option(ENABLE_SSSE3 "Enable Intel SSSE3 instructions" OFF)
option(ENABLE_SSE4.1 "Enable Intel SSE4.1 instructions" OFF)
option(ENABLE_SSE4.2 "Enable Intel SSE4.2 instructions" OFF)
option(ENABLE_AVX  "Enable Intel AVX instructions" OFF)
option(ENABLE_AVX2 "Enable Intel AVX2 instructions" OFF)
option(ENABLE_AVX512F "Enable Intel AVX512F instructions" OFF)
option(ENABLE_FMA  "Enable Intel FMA instructions" OFF)
option(ENABLE_FAISS "Enable Faiss lib" OFF)

# OpenMP support
if(ENABLE_OPENMP)
  find_package(OpenMP)
  if(OPENMP_FOUND)
    list(APPEND TARGETS_CFLAGS ${OpenMP_C_FLAGS})
    list(APPEND TARGETS_CXXFLAGS ${OpenMP_CXX_FLAGS})
  endif()
endif()

include(CheckCCompilerFlag)
if(NOT MSVC)
  if(ENABLE_AVX512F)
    CHECK_C_COMPILER_FLAG("-mavx512f" COMPILER_SUPPORT_AVX512F)
    if(COMPILER_SUPPORT_AVX512F)
      list(APPEND TARGETS_CFLAGS -mavx512f)
      list(APPEND TARGETS_CXXFLAGS -mavx512f)
    endif()
  elseif(ENABLE_AVX2)
    CHECK_C_COMPILER_FLAG("-mavx2" COMPILER_SUPPORT_AVX2)
    if(COMPILER_SUPPORT_AVX2)
      list(APPEND TARGETS_CFLAGS -mavx2)
      list(APPEND TARGETS_CXXFLAGS -mavx2)
    endif()
  elseif(ENABLE_AVX)
    CHECK_C_COMPILER_FLAG("-mavx" COMPILER_SUPPORT_AVX)
    if(COMPILER_SUPPORT_AVX)
      list(APPEND TARGETS_CFLAGS -mavx)
      list(APPEND TARGETS_CXXFLAGS -mavx)
    endif()
  elseif(ENABLE_SSE4.2)
    CHECK_C_COMPILER_FLAG("-msse4.2" COMPILER_SUPPORT_SSE4.2)
    if(COMPILER_SUPPORT_SSE4.2)
      list(APPEND TARGETS_CFLAGS -msse4.2)
      list(APPEND TARGETS_CXXFLAGS -msse4.2)
    endif()
  elseif(ENABLE_SSE4.1)
    CHECK_C_COMPILER_FLAG("-msse4.1" COMPILER_SUPPORT_SSE4.1)
    if(COMPILER_SUPPORT_SSE4.1)
      list(APPEND TARGETS_CFLAGS -msse4.1)
      list(APPEND TARGETS_CXXFLAGS -msse4.1)
    endif()
  elseif(ENABLE_SSSE3)
    CHECK_C_COMPILER_FLAG("-mssse3" COMPILER_SUPPORT_SSSE3)
    if(COMPILER_SUPPORT_SSSE3)
      list(APPEND TARGETS_CFLAGS -mssse3)
      list(APPEND TARGETS_CXXFLAGS -mssse3)
    endif()
  elseif(ENABLE_SSE3)
    CHECK_C_COMPILER_FLAG("-msse3" COMPILER_SUPPORT_SSE3)
    if(COMPILER_SUPPORT_SSE3)
      list(APPEND TARGETS_CFLAGS -msse3)
      list(APPEND TARGETS_CXXFLAGS -msse3)
    endif()
  elseif(ENABLE_SSE2)
    CHECK_C_COMPILER_FLAG("-msse2" COMPILER_SUPPORT_SSE2)
    if(COMPILER_SUPPORT_SSE2)
      list(APPEND TARGETS_CFLAGS -msse2)
      list(APPEND TARGETS_CXXFLAGS -msse2)
    endif()
  elseif(ENABLE_SSE)
    CHECK_C_COMPILER_FLAG("-msse" COMPILER_SUPPORT_SSE)
    if(COMPILER_SUPPORT_SSE)
      list(APPEND TARGETS_CFLAGS -msse)
      list(APPEND TARGETS_CXXFLAGS -msse)
    endif()
  endif()
  if(ENABLE_FMA)
    CHECK_C_COMPILER_FLAG("-mfma" COMPILER_SUPPORT_FMA)
    if(COMPILER_SUPPORT_FMA)
      list(APPEND TARGETS_CFLAGS -mfma)
      list(APPEND TARGETS_CXXFLAGS -mfma)
    endif()
  endif()
else()
  if(ENABLE_AVX2)
    CHECK_C_COMPILER_FLAG("/arch:AVX2" COMPILER_SUPPORT_AVX2)
    if(COMPILER_SUPPORT_AVX2)
      list(APPEND TARGETS_CFLAGS /arch:AVX2)
      list(APPEND TARGETS_CXXFLAGS /arch:AVX2)
    endif()
  elseif(ENABLE_AVX)
    CHECK_C_COMPILER_FLAG("/arch:AVX" COMPILER_SUPPORT_AVX)
    if(COMPILER_SUPPORT_AVX)
      list(APPEND TARGETS_CFLAGS /arch:AVX)
      list(APPEND TARGETS_CXXFLAGS /arch:AVX)
    endif()
  elseif(ENABLE_SSE4.2 OR ENABLE_SSE4.1 OR ENABLE_SSE3 OR ENABLE_SSSE3 OR ENABLE_SSE2)
    CHECK_C_COMPILER_FLAG("/arch:SSE2" COMPILER_SUPPORT_SSE2)
    if(COMPILER_SUPPORT_SSE2)
      list(APPEND TARGETS_CFLAGS /arch:SSE2)
      list(APPEND TARGETS_CXXFLAGS /arch:SSE2)
    endif()
  elseif(ENABLE_SSE)
    CHECK_C_COMPILER_FLAG("/arch:SSE" COMPILER_SUPPORT_SSE)
    if(COMPILER_SUPPORT_SSE)
      list(APPEND TARGETS_CFLAGS /arch:SSE)
      list(APPEND TARGETS_CXXFLAGS /arch:SSE)
    endif()
  endif()
endif()
