package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "lve_common",
    includes = [".."],
    srcs = glob([
        "*.h",
    ]),
    hdrs = glob([
        "*.h",
    ]),
)
